parameters:
    toggl_settings:
      service_name: 'DA Toggl API'
      default_entry_name: Urlop
      default_project_id: 0
      default_task_id: 0
      mapping:
        projects:
          0: 0
        tasks:
          0:
            name: Urlop
            id: 0
    toggl.api.class: TogglBundle\Services\Toggl
    toggl.service.class: TogglBundle\Services\Service